# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
      - uses: actions/checkout@v2
      - name: Unity Build Action
  # You may pin to the exact commit or the version.
  # uses: yukiarrr/unity-build-action@92522bf02883fc225c86ff0c522c1c8051e83c1e
        uses: yukiarrr/unity-build-action@v0.6.1
        with:
          # For example, 2018.4.16f1
          unity-version: 2020.1.6f1
          # Choose Android, iOS, Mac, Windows, or WebGL
          build-target: Android
          # Unity project path
          project-path: Asset
          # Use by -executeMethod
          execute-method: UnityBuild.BatchBuild.Build
      - name: Unity - Builder
        # You may pin to the exact commit or the version.
        # uses: game-ci/unity-builder@c8202c01e7dfe4de0e897b26cb2ca1cc363e4ad4
        uses: game-ci/unity-builder@v2.0-alpha-6
